# Generated by Django 2.2.5 on 2019-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20191005_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_d',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_d',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
