# Generated by Django 2.2.5 on 2019-10-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20191006_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_pub_date']},
        ),
    ]
