# Generated by Django 2.2.5 on 2019-10-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20191006_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_pub_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
